{
 "title": "Spring Batch Prometheus",
 "description": "Dashboard for Spring Batch applications instrumented with Micrometer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "TimeRate",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Spring Batch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"batch-processing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(spring_batch_job_seconds_max{job=\"batch-processing\"})",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Job execution rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(spring_batch_job_seconds_count[$TimeRate])",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Job failure rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count(sum(rate(spring_batch_job_seconds_count{spring_batch_job_status=\"FAILED\"}[$TimeRate])) by (spring_batch_job_name, spring_batch_job_status)) / count(sum(rate(spring_batch_job_seconds_count[$TimeRate])) by (spring_batch_job_name, spring_batch_job_status))",
     "legendFormat": "{{name}} {{status}}"
    }
   ]
  },
  {
   "title": "Item read throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_batch_item_read_seconds_count[$TimeRate])",
     "legendFormat": "read {{status}}"
    }
   ]
  },
  {
   "title": "Item write throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_batch_chunk_write_seconds_count[$TimeRate])",
     "legendFormat": "write {{status}}"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(jvm_memory_used_bytes{application=\"batch-processing\"}[$TimeRate])) / sum(rate(process_resident_memory_bytes{application=\"batch-processing\"}[$TimeRate])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}