spring.application.name = batch-processing

spring.datasource.url=jdbc:postgresql://postgresdb:5432/productsdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.batch.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.batch.jdbc.table-prefix=BATCH_

management.prometheus.metrics.export.enabled=true
management.prometheus.metrics.export.pushgateway.enabled=true
management.prometheus.metrics.export.pushgateway.address=host.docker.internal:9091
management.prometheus.metrics.export.pushgateway.push-rate=1ms
management.prometheus.metrics.export.pushgateway.job=${spring.application.name}
management.endpoints.web.exposure.include=env,health,info,metrics,mappings,prometheus
management.metrics.tags.application=${spring.application.name}
management.endpoint.health.show-details=always
management.health.probes.enabled=true

logging.level.com.example.batchprocessing=DEBUG