# Стадия сборки
FROM apache/airflow:2.5.3
USER root
# Глобальные переменные стадии сборки
ENV AIRFLOW_IMAGE_NAME = 'espp-apache/airflow:2.5.3'
# Настрока регистри (можно закомментировать при локальной сборке)
#COPY ./deployment/apt/apt.conf /etc/apt/apt.conf
#COPY ./deployment/apt/sources.list /etc/apt/sources.list

# Установка бинарных пакетов Oracle драйверов
RUN apt update \
    && apt install -y unixodbc unzip libgl1 libaio1 wget build-essential libc6-dev freetds-dev freetds-bin tdsodbc

COPY ./drivers/oracle/ /tmp/
COPY ./requirements.txt /tmp/

RUN unzip -o /tmp/instantclient-basic-linux.x64-11.2.0.4.0.zip -d /opt/oracle/ && \
    ln -sf /opt/oracle/instantclient_11_2 /opt/oracle/instantclient && \
    ln -sf /opt/oracle/instantclient/libclntsh.so.11.1 /opt/oracle/instantclient/libclntsh.so

# Прописываем библиотеки в окружение
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/oracle/instantclient"

# ARG FREETDS_VERSION='1.2.18'	

# RUN wget https://www.freetds.org/files/stable/freetds-${FREETDS_VERSION}.tar.gz \
#     && tar xfv freetds-${FREETDS_VERSION}.tar.gz \ 
#     && cd freetds-${FREETDS_VERSION} \
#     && ./configure --prefix=/opt --disable-dependency-tracking  --with-unixodbc \
#     && make V=1 \
#     && make install

# RUN echo "[FreeTDS]\nDescription=FreeTDS\nDriver=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so" >> /etc/odbcinst.ini \
#     && odbcinst -i -d -f /etc/odbcinst.ini
   # && sed -i 's/auto/4.2/' /opt/etc/freetds.conf


# RUN echo "[FreeTDS]\nDescription=FreeTDS\nDriver=/opt/lib/libtdsodbc.so" >> /etc/odbcinst.ini \
#     && odbcinst -i -d -f /etc/odbcinst.ini \
#     && sed -i 's/auto/4.2/' /opt/etc/freetds.conf


USER airflow
RUN pip install --no-cache-dir -r /tmp/requirements.txt

USER root
RUN apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get remove -y wget unzip && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /var/lib/log/* /tmp/* /var/tmp/*
# RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf \
#     && sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/ssl/openssl.cnf